// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1638278939);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1638278699);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1638278819);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1638278729);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1638279059);
user_pref("browser.cache.disk.capacity", 153600);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1638278940);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.13.0");
user_pref("extensions.lastPlatformVersion", "78.13.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"0e7d699d-005f-4cc5-b51d-a33bf6427f0f\"}");
user_pref("idle.lastDailyNotification", 1638278938);
user_pref("mail.ui-rdf.version", 23);
user_pref("mailnews.database.global.datastore.id", "b850044d-f135-429b-9b2a-72c05de2a8e");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "중요");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "직장");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "개인");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "할일");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "연기");
user_pref("mailnews.tags.version", 2);
user_pref("places.database.lastMaintenance", 1638278938);
user_pref("places.history.expiration.transient_current_max_pages", 15133);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("security.sandbox.plugin.tempDirSuffix", "0c6a3c65-73c5-4169-a99b-7be01b6fe4ce");
user_pref("services.blocklist.addons.checked", 1638278824);
user_pref("services.settings.clock_skew_seconds", -5);
user_pref("services.settings.last_etag", "\"1638262787579\"");
user_pref("services.settings.last_update_seconds", 1638278824);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1638278824);
user_pref("services.settings.main.hijack-blocklists.last_check", 1638278824);
user_pref("services.settings.main.language-dictionaries.last_check", 1638278824);
user_pref("services.settings.main.search-config.last_check", 1638278824);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1638278824);
user_pref("services.settings.main.sites-classification.last_check", 1638278824);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1638278824);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1638278938);
user_pref("toolkit.telemetry.cachedClientID", "158fd0db-edfe-44b5-9e76-3f86f820ae99");
user_pref("toolkit.telemetry.previousBuildID", "20210802223056");
