// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.media.peerconnection.mtransport_process", true);
user_pref("app.normandy.startupRolloutPrefs.network.process.enabled", true);
user_pref("app.normandy.user_id", "2e3244ef-c99f-4f9a-a3ce-b1362ed8ba45");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1638280806);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1638280787);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1638280782);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1638280775);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 117);
user_pref("browser.newtabpage.activity-stream.impressionId", "{bfbe088a-6b9e-4f52-8eee-afbca247d7db}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1638280780);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1638280811489");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1638282613489");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1638280788336");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1638302388336");
user_pref("browser.search.region", "KR");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1638280786");
user_pref("browser.startup.homepage_override.buildID", "20210927210923");
user_pref("browser.startup.homepage_override.mstone", "93.0");
user_pref("browser.startup.lastColdStartupCheck", 1638280778);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1638280786176");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "93.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "KR");
user_pref("dom.push.userAgentID", "7c0cd702583e4ea2b3c436d689697f17");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210927210923");
user_pref("extensions.lastAppVersion", "93.0");
user_pref("extensions.lastPlatformVersion", "93.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"ba319010-126f-4ec9-8ac5-5d9ef3651391\",\"formautofill@mozilla.org\":\"795e5190-7ca6-41db-86b3-16c7550cf99b\",\"pictureinpicture@mozilla.org\":\"f97ed229-25f8-46e0-8bb4-fd10750510a6\",\"screenshots@mozilla.org\":\"925cf02f-26c2-46eb-bf84-5f9029be0a16\",\"webcompat-reporter@mozilla.org\":\"23cd9053-6c5b-4233-967c-d58258b1cd47\",\"webcompat@mozilla.org\":\"df1040e5-754d-4406-a5d0-87cf64ad052f\",\"default-theme@mozilla.org\":\"79c37ac3-a949-446f-b3bb-214a738d21ba\",\"google@search.mozilla.org\":\"e45624fe-7ab4-453d-a04e-04a6ffaee504\",\"daum-kr@search.mozilla.org\":\"37282cdf-af55-4cd7-9a46-9e5dfb7a9837\",\"wikipedia@search.mozilla.org\":\"9cdf73ca-eb76-4aec-a454-e898e1b286a1\",\"naver-kr@search.mozilla.org\":\"7544cfab-a7bb-4f4a-8e4e-6b8763c69bb0\",\"ddg@search.mozilla.org\":\"8fda6f54-09c5-4fe2-902e-7c0f4ef3d84d\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1638280787);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "66fbb3d2-572e-409e-9966-2c4bdd6a991c");
user_pref("toolkit.telemetry.cachedClientID", "da32fc69-d6f9-4d24-b5e4-09ae59f985b9");
user_pref("toolkit.telemetry.previousBuildID", "20210927210923");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
